### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by SzeligBalazs** [MateGames/MyEpamGame2#2]
Hello @MateGames!

**Fork**oltam a repodat, hogy egy kicsit hozzájáruljak én is a projekthez ha akarod, de nincs a repoban a `mateo` python library.

**Hibaüzenet**:
```bash
> python .\mian.py  
pygame 2.5.2 (SDL 2.28.3, Python 3.12.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "E:\dev\python\MyEpamGame2\mian.py", line 2, in <module>
    import mateo
ModuleNotFoundError: No module named 'mateo'
```

Kérlek töltsd fel a repoba. 
Thx
*Balage*

**Comment by MateGames** [comment]
Hello @SzeligBalazs!

A játék nem használja már 'mateo' python library de mégis megpróbálja importálni amit javitok.

Köszönöm hogy jelezted
*Mateo*
